version: '3.8'

services:
  convos:
    image: ghcr.io/convos-chat/convos:stable
    container_name: convos
    ports:
      - "2021:3000"
    volumes:
      - ./convos-data:/data
    restart: unless-stopped
